### ISSUE TITLE
No such files or directory

### ISSUE THREAD

**Issue by anthony-git** [microsoftgraph/meeting-moderator-sample#3]
![2020-07-06_19h44_13](https://user-images.githubusercontent.com/54057007/86604748-67400c00-bfc3-11ea-814b-9f4351b96292.png)

When I run 'npm install' i get the above error. 'stating no such files or directory'

**Comment by nmetulev** [comment]
Hi @anthony-git, are you able to share repro steps so I can try to replicate this behavior?  Also, what is your environment (node version, os, shell, etc)?

**Comment by anthony-git** [comment]
I have downloaded the zip file and extracted to my local drive and changed the path and ran the npm install command
Node v8.11.4
OS - windows 10
windows powershell

**Comment by nmetulev** [comment]
Thanks for that info @anthony-git. I'm still having trouble reproducing the issue with that environment by downloading the zip file. I'd try deleting the folder and trying again and see if that has an effect. You can also try updating node to v10 or v12 and see if that changes anything.

**Comment by anthony-git** [comment]
HI @nmetulev, I have updated the node to v12 and now am able to run it. Thanks

**Comment by nmetulev** [comment]
Glad to hear it, thanks for letting us know.
